source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 7.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "sidekiq", "~> 7.0"
gem "connection_pool", "~> 2.4"
gem "rack-cors"
gem "bootsnap", require: false
gem "faraday", "~> 2.0"
gem "faraday-multipart"
gem "playwright-ruby-client", "~> 1.47"
gem "websocket-client-simple"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
